control_server:
  ros__parameters:
    server_name: control_server
    master_name: csm_master
    watchdog_interval_ms: 50
    status_timer_interval_ms: 100
    csm_timeout_ms: 600
    csm_disconnect_timeout_ms: 6000
    log_output: true
