/**
 * This file implements the ControlServer class, which received control signal, 
 *  and transfers the control signal to motion command.
 * The control signal have CSM to manage the Sinks that generated by the remote CSM.
 * The control server has a output signal switch mechanism, which can switch output control 
 *  signal between different Sinks by manual (select index) or by fallback with priority.
 * If the current active Sink has timeout, the fallback mechanism will select the Sink with 
 *  highest priority as active Sink. If no Sink is active, output emergency stop command.
 * If any of the Sinks sends a emergency stop command, output emergency stop command 
 *  immediately and switch the active Sink to the one with highest priority.
 * Cause control signal e.g. Joy or Twist did not have a standard emergency stop command, 
 *  so the emergency stop command should be defined by the user in function called after 
 *  control server receives the control signal. E.g. For Joy, the emergency stop command 
 *  can be defined as buttons[0], buttons[1], buttons[2] and buttons[3] are all -99. For Twist, the 
 *  emergency stop command can be defined as linear.z, angular.x and angular.y are all -99.
 * We should define a request active sink command for the Source side can request to set0 
 *  the active Sink to itself. The request active sink command e.g. Joy can be defined as 
 *  buttons[0], buttons[1], buttons[2] and buttons[3] are all 99. Twist can be defined as 
 *  linear.z, angular.x and angular.y are all 99. If the request Source has higher priority 
 *  than the current active Sink, switch the active Sink to the request Source.
 */

#include <rclcpp/rclcpp.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include "unitree_api/msg/request.hpp"
#include "nlohmann/json.hpp"
#include "rv2_server_control/control_server.h"
#include "rclcpp_components/register_node_macro.hpp"

// ── Unitree Sport API IDs ─────────────────────────────────────────────────────
//  Defined here to avoid depending on the full SportClient library.
//  Values match ROBOT_SPORT_API_ID_* constants in ros2_b2_sport_client.h.
static constexpr int64_t SPORT_API_ID_DAMP          = 1001;
static constexpr int64_t SPORT_API_ID_STOPMOVE       = 1003;
static constexpr int64_t SPORT_API_ID_STANDUP        = 1004;
static constexpr int64_t SPORT_API_ID_STANDDOWN      = 1005;
static constexpr int64_t SPORT_API_ID_RECOVERY_STAND = 1006;
static constexpr int64_t SPORT_API_ID_MOVE           = 1008;
static constexpr int64_t SPORT_API_ID_SWITCH_GAIT    = 1011;

// ── Application-specific signal conventions for Joy ───────────────────────────
//
//  Emergency stop : buttons[0..3] all == -99
//  Request active : buttons[0..3] all == 99
//
static bool joyIsEmergencyStop(const sensor_msgs::msg::Joy& joy)
{
    if (static_cast<int>(joy.buttons.size()) < 4) return false;
    return joy.buttons[0] == -99 && joy.buttons[1] == -99 &&
           joy.buttons[2] == -99 && joy.buttons[3] == -99;
}

static bool joyIsRequestActive(const sensor_msgs::msg::Joy& joy)
{
    if (static_cast<int>(joy.buttons.size()) < 4) return false;
    return joy.buttons[0] == 99 && joy.buttons[1] == 99 &&
           joy.buttons[2] == 99 && joy.buttons[3] == 99;
}

// ── Joy → unitree_api::msg::Request ─────────────────────────────────────────
//
//  Button mode mapping (mirrors option_list in b2w_sport_client.cpp).
//  First pressed button wins; the matching command is returned immediately.
//  Buttons are standard gamepad values (0 = released, 1 = pressed).
//  Emergency-stop sentinels (-99) and request-active sentinels (99) are
//  handled by joyIsEmergencyStop / joyIsRequestActive before this is called.
//
//    buttons[0] = 1  →  Damp          (api_id 1001)
//    buttons[1] = 1  →  StandUp       (api_id 1004)
//    buttons[2] = 1  →  StandDown     (api_id 1005)
//    buttons[6] = 1  →  StopMove      (api_id 1003)
//    buttons[7] = 1  →  SwitchGait 0  (api_id 1011, {"data":0})
//    buttons[8] = 1  →  SwitchGait 1  (api_id 1011, {"data":1})
//    buttons[9] = 1  →  RecoveryStand (api_id 1006)
//
//  Axes mapping (first four axes, each unipolar 0–1):
//    axes[0] → forward   (+vx)
//    axes[1] → backward  (-vx)
//    axes[2] → turn left (+vyaw)
//    axes[3] → turn right(-vyaw)
//  Combined: vx = axes[0] - axes[1],  vy = 0,  vyaw = axes[2] - axes[3]
//  Builds a MOVE request (api_id 1008) with JSON {"x":vx, "y":0, "z":vyaw}.
//
static unitree_api::msg::Request joyToUnitreeRequest(const sensor_msgs::msg::Joy& joy)
{
    const auto& btn = joy.buttons;
    const size_t nb  = btn.size();

    unitree_api::msg::Request req;

    // ── Button mode commands ─────────────────────────────────────────────────
    if (nb > 0 && btn[0] == 1) {
        req.header.identity.api_id = SPORT_API_ID_DAMP;
        return req;
    }
    if (nb > 1 && btn[1] == 1) {
        req.header.identity.api_id = SPORT_API_ID_STANDUP;
        return req;
    }
    if (nb > 2 && btn[2] == 1) {
        req.header.identity.api_id = SPORT_API_ID_STANDDOWN;
        return req;
    }
    if (nb > 6 && btn[6] == 1) {
        req.header.identity.api_id = SPORT_API_ID_STOPMOVE;
        return req;
    }
    if (nb > 7 && btn[7] == 1) {
        req.header.identity.api_id = SPORT_API_ID_SWITCH_GAIT;
        req.parameter = nlohmann::json{{"data", 0}}.dump();
        return req;
    }
    if (nb > 8 && btn[8] == 1) {
        req.header.identity.api_id = SPORT_API_ID_SWITCH_GAIT;
        req.parameter = nlohmann::json{{"data", 1}}.dump();
        return req;
    }
    if (nb > 9 && btn[9] == 1) {
        req.header.identity.api_id = SPORT_API_ID_RECOVERY_STAND;
        return req;
    }

    // ── Default: MOVE from axes[0..3] ───────────────────────────────────────
    const auto& ax  = joy.axes;
    const float vx   = (ax.size() > 1) ? (ax[0] - ax[1]) : (ax.size() > 0 ? ax[0] : 0.0f);
    const float vyaw = (ax.size() > 3) ? (ax[2] - ax[3]) : 0.0f;

    nlohmann::json js;
    js["x"] = vx;
    js["y"] = 0.0f;
    js["z"] = vyaw;

    req.header.identity.api_id = SPORT_API_ID_MOVE;
    req.parameter              = js.dump();
    return req;
}

// ── Twist signal conventions ─────────────────────────────────────────────────
//
//  Emergency stop : linear.z == -99  AND  angular.x == -99  AND  angular.y == -99
//  Request active : linear.z ==  99  AND  angular.x ==  99  AND  angular.y ==  99
//
static bool twistIsEmergencyStop(const geometry_msgs::msg::Twist& twist)
{
    return twist.linear.z  == -99.0 &&
           twist.angular.x == -99.0 &&
           twist.angular.y == -99.0;
}

static bool twistIsRequestActive(const geometry_msgs::msg::Twist& twist)
{
    return twist.linear.z  == 99.0 &&
           twist.angular.x == 99.0 &&
           twist.angular.y == 99.0;
}

// ── Twist → unitree_api::msg::Request (Move command) ─────────────────────────
//
//  Field mapping:
//    linear.x  → vx   (forward / backward)
//    linear.y  → vy   (lateral strafe)
//    angular.z → vyaw (rotation)
//
//  Builds a MOVE request (api_id = 1008) with JSON payload
//  {"x": vx, "y": vy, "z": vyaw}.
//
static unitree_api::msg::Request twistToUnitreeRequest(const geometry_msgs::msg::Twist& twist)
{
    nlohmann::json js;
    js["x"] = static_cast<float>(twist.linear.x);
    js["y"] = static_cast<float>(twist.linear.y);
    js["z"] = static_cast<float>(twist.angular.z);

    unitree_api::msg::Request req;
    req.header.identity.api_id = SPORT_API_ID_MOVE;
    req.parameter              = js.dump();
    return req;
}

// ── Emergency stop → unitree_api::msg::Request (StopMove command) ────────────
//
//  Builds a STOPMOVE request (api_id = 1003) with no parameters.
//
static unitree_api::msg::Request makeStopRequest()
{
    unitree_api::msg::Request req;
    req.header.identity.api_id = SPORT_API_ID_STOPMOVE;
    return req;
}


// ── ControlServerNode ─────────────────────────────────────────────────────────

class ControlServerNode : public rclcpp::Node
{
public:
    explicit ControlServerNode(const rclcpp::NodeOptions & options)
        : Node("control_server", options)
    {
        // Declare parameters
        this->declare_parameter<std::string>("server_name",              "control_server");
        this->declare_parameter<int64_t>    ("output_interval_ms",       50);
        this->declare_parameter<int64_t>    ("status_timer_interval_ms", 1000);

        const std::string serverName          = this->get_parameter("server_name").as_string();
        const int64_t     outputIntervalMs    = this->get_parameter("output_interval_ms").as_int();
        const int64_t     statusTimerMs       = this->get_parameter("status_timer_interval_ms").as_int();

        // Publisher: Unitree sport API request on the standard topic
        reqPub_ = this->create_publisher<unitree_api::msg::Request>(
            "/api/sport/request", rclcpp::QoS(10));

        // Build ControlServer config
        rv2_interfaces::ControlServer::Config cfg;
        cfg.name                  = serverName;
        cfg.outputIntervalNs      = outputIntervalMs * 1'000'000LL;
        cfg.statusTimerIntervalMs = statusTimerMs;

        server_ = std::make_unique<rv2_interfaces::ControlServer>(this, std::move(cfg));

        // Register Joy type config
        rv2_interfaces::ControlServer::TypeConfig<sensor_msgs::msg::Joy> joyCfg;
        joyCfg.isEmergencyStop = joyIsEmergencyStop;
        joyCfg.isRequestActive = joyIsRequestActive;

        joyCfg.outputCb = [this](const sensor_msgs::msg::Joy& joy,
                                 const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            auto req = joyToUnitreeRequest(joy);
            reqPub_->publish(req);

            const int64_t api = req.header.identity.api_id;
            if (api == SPORT_API_ID_MOVE) {
                RCLCPP_DEBUG(this->get_logger(),
                    "[cmd/joy] MOVE ch='%s' param=%s",
                    info.channel_name.c_str(), req.parameter.c_str());
            } else {
                const char * cmd = "UNKNOWN";
                switch (api) {
                case SPORT_API_ID_DAMP:           cmd = "DAMP";           break;
                case SPORT_API_ID_STANDUP:        cmd = "STAND_UP";       break;
                case SPORT_API_ID_STANDDOWN:      cmd = "STAND_DOWN";     break;
                case SPORT_API_ID_STOPMOVE:       cmd = "STOP_MOVE";      break;
                case SPORT_API_ID_SWITCH_GAIT:    cmd = "SWITCH_GAIT";    break;
                case SPORT_API_ID_RECOVERY_STAND: cmd = "RECOVERY_STAND"; break;
                default: break;
                }
                if (api == SPORT_API_ID_DAMP) {
                    RCLCPP_WARN(this->get_logger(),
                        "[cmd/joy] %s  ch='%s'%s",
                        cmd, info.channel_name.c_str(),
                        req.parameter.empty() ? "" : ("  param=" + req.parameter).c_str());
                } else {
                    RCLCPP_INFO(this->get_logger(),
                        "[cmd/joy] %s  ch='%s'%s",
                        cmd, info.channel_name.c_str(),
                        req.parameter.empty() ? "" : ("  param=" + req.parameter).c_str());
                }
            }
        };

        joyCfg.emergencyStopCb = [this](const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            reqPub_->publish(makeStopRequest());
            RCLCPP_WARN(this->get_logger(),
                "[E-STOP/joy] STOP_MOVE sent. Triggered by ch='%s'",
                info.channel_name.empty() ? "(no active sink)" : info.channel_name.c_str());
        };

        server_->registerTypeConfig(std::move(joyCfg));

        // Register Twist type config
        rv2_interfaces::ControlServer::TypeConfig<geometry_msgs::msg::Twist> twistCfg;
        twistCfg.isEmergencyStop = twistIsEmergencyStop;
        twistCfg.isRequestActive = twistIsRequestActive;

        twistCfg.outputCb = [this](const geometry_msgs::msg::Twist& twist,
                                   const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            auto req = twistToUnitreeRequest(twist);
            reqPub_->publish(req);

            RCLCPP_DEBUG(this->get_logger(),
                "[cmd/twist] MOVE ch='%s' param=%s",
                info.channel_name.c_str(), req.parameter.c_str());
        };

        twistCfg.emergencyStopCb = [this](const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            reqPub_->publish(makeStopRequest());
            RCLCPP_WARN(this->get_logger(),
                "[E-STOP/twist] STOP_MOVE sent. Triggered by ch='%s'",
                info.channel_name.empty() ? "(no active sink)" : info.channel_name.c_str());
        };

        server_->registerTypeConfig(std::move(twistCfg));

        RCLCPP_INFO(this->get_logger(),
            "ControlServerNode started. Listening on '%s/control_signal_reg'. "
            "Publishing Unitree sport requests at %ld ms interval.",
            serverName.c_str(), static_cast<long>(outputIntervalMs));
    }

private:
    rclcpp::Publisher<unitree_api::msg::Request>::SharedPtr reqPub_;
    std::unique_ptr<rv2_interfaces::ControlServer> server_;
};

RCLCPP_COMPONENTS_REGISTER_NODE(ControlServerNode)

