/**
 * This file implements the ControlServer class, which received control signal, 
 *  and transfers the control signal to motion command.
 * The control signal have CSM to manage the Sinks that generated by the remote CSM.
 * The control server has a output signal switch mechanism, which can switch output control 
 *  signal between different Sinks by manual (select index) or by fallback with priority.
 * If the current active Sink has timeout, the fallback mechanism will select the Sink with 
 *  highest priority as active Sink. If no Sink is active, output emergency stop command.
 * If any of the Sinks sends a emergency stop command, output emergency stop command 
 *  immediately and switch the active Sink to the one with highest priority.
 * Cause control signal e.g. Joy or Twist did not have a standard emergency stop command, 
 *  so the emergency stop command should be defined by the user in function called after 
 *  control server receives the control signal. E.g. For Joy, the emergency stop command 
 *  can be defined as buttons[0], buttons[1], buttons[2] and buttons[3] are all -99. For Twist, the 
 *  emergency stop command can be defined as linear.z, angular.x and angular.y are all -99.
 * We should define a request active sink command for the Source side can request to set0 
 *  the active Sink to itself. The request active sink command e.g. Joy can be defined as 
 *  buttons[0], buttons[1], buttons[2] and buttons[3] are all 99. Twist can be defined as 
 *  linear.z, angular.x and angular.y are all 99. If the request Source has higher priority 
 *  than the current active Sink, switch the active Sink to the request Source.
 */

#include <rclcpp/rclcpp.hpp>
#include <sensor_msgs/msg/joy.hpp>
#include <geometry_msgs/msg/twist.hpp>
#include "ros2_b2_sport_client.h"
#include "rv2_server_control/control_server.h"
#include "rv2_server_control/control_signal_detect.h"
#include "rclcpp_components/register_node_macro.hpp"



// ── ControlServerNode ─────────────────────────────────────────────────────────

class ControlServerNode : public rclcpp::Node
{
public:
    explicit ControlServerNode(const rclcpp::NodeOptions & options)
        : Node("control_server", options)
        , sportClient_(this)
    {
        // Declare parameters
        this->declare_parameter<std::string>("server_name",              "control_server");
        this->declare_parameter<int64_t>    ("output_interval_ms",       50);
        this->declare_parameter<int64_t>    ("status_timer_interval_ms", 1000);

        const std::string serverName          = this->get_parameter("server_name").as_string();
        const int64_t     outputIntervalMs    = this->get_parameter("output_interval_ms").as_int();
        const int64_t     statusTimerMs       = this->get_parameter("status_timer_interval_ms").as_int();

        // Build ControlServer config
        rv2_interfaces::rv2_server_control::ControlServer::Config cfg;
        cfg.name                  = serverName;
        cfg.outputIntervalNs      = outputIntervalMs * 1'000'000LL;
        cfg.statusTimerIntervalMs = statusTimerMs;

        server_ = std::make_unique<rv2_interfaces::rv2_server_control::ControlServer>(this, std::move(cfg));

        // Register Joy type config
        rv2_interfaces::rv2_server_control::ControlServer::TypeConfig<sensor_msgs::msg::Joy> joyCfg;
        joyCfg.outputCb = [this](const sensor_msgs::msg::Joy& joy,
                                 const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            unitree_api::msg::Request req;
            const auto & btn = joy.buttons;
            const size_t nb  = btn.size();

            if      (nb > 0 && btn[0] == 1) { sportClient_.Damp(req); }
            else if (nb > 1 && btn[1] == 1) { sportClient_.StandUp(req); }
            else if (nb > 2 && btn[2] == 1) { sportClient_.StandDown(req); }
            else if (nb > 6 && btn[6] == 1) { sportClient_.StopMove(req); }
            else if (nb > 9 && btn[9] == 1) { sportClient_.RecoveryStand(req); }
            else if (nb > 7 && btn[7] == 1) { sportClient_.SwitchGait(req, 0); }
            else if (nb > 8 && btn[8] == 1) { sportClient_.SwitchGait(req, 1); }
            else {
                const auto & ax   = joy.axes;
                const float  vx   = (ax.size() > 1) ? (ax[0] - ax[1]) : (ax.size() > 0 ? ax[0] : 0.0f);
                const float  vyaw = (ax.size() > 3) ? (ax[2] - ax[3]) : 0.0f;
                sportClient_.Move(req, vx, 0.0f, vyaw);
            }

            const int32_t api = req.header.identity.api_id;
            if (api == ROBOT_SPORT_API_ID_MOVE) {
                RCLCPP_DEBUG(this->get_logger(),
                    "[cmd/joy] MOVE ch='%s' param=%s",
                    info.channel_name.c_str(), req.parameter.c_str());
            } else {
                const char * cmd = "UNKNOWN";
                switch (api) {
                case ROBOT_SPORT_API_ID_DAMP:          cmd = "DAMP";           break;
                case ROBOT_SPORT_API_ID_STANDUP:       cmd = "STAND_UP";       break;
                case ROBOT_SPORT_API_ID_STANDDOWN:     cmd = "STAND_DOWN";     break;
                case ROBOT_SPORT_API_ID_STOPMOVE:      cmd = "STOP_MOVE";      break;
                case ROBOT_SPORT_API_ID_SWITCHGAIT:    cmd = "SWITCH_GAIT";    break;
                case ROBOT_SPORT_API_ID_RECOVERYSTAND: cmd = "RECOVERY_STAND"; break;
                default: break;
                }
                if (api == ROBOT_SPORT_API_ID_DAMP) {
                    RCLCPP_WARN(this->get_logger(),
                        "[cmd/joy] %s  ch='%s'%s",
                        cmd, info.channel_name.c_str(),
                        req.parameter.empty() ? "" : ("  param=" + req.parameter).c_str());
                } else {
                    RCLCPP_INFO(this->get_logger(),
                        "[cmd/joy] %s  ch='%s'%s",
                        cmd, info.channel_name.c_str(),
                        req.parameter.empty() ? "" : ("  param=" + req.parameter).c_str());
                }
            }
        };

        joyCfg.emergencyStopCb = [this](const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            unitree_api::msg::Request req;
            sportClient_.StopMove(req);
            RCLCPP_WARN(this->get_logger(),
                "[E-STOP/joy] STOP_MOVE sent. Triggered by ch='%s'",
                info.channel_name.empty() ? "(no active sink)" : info.channel_name.c_str());
        };

        server_->registerTypeConfig(std::move(joyCfg));

        // Register Twist type config
        rv2_interfaces::rv2_server_control::ControlServer::TypeConfig<geometry_msgs::msg::Twist> twistCfg;
        twistCfg.outputCb = [this](const geometry_msgs::msg::Twist& twist,
                                   const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            unitree_api::msg::Request req;
            sportClient_.Move(req,
                static_cast<float>(twist.linear.x),
                static_cast<float>(twist.linear.y),
                static_cast<float>(twist.angular.z));
            RCLCPP_DEBUG(this->get_logger(),
                "[cmd/twist] MOVE ch='%s' param=%s",
                info.channel_name.c_str(), req.parameter.c_str());
        };

        twistCfg.emergencyStopCb = [this](const rv2_interfaces::msg::ControlSignalInfo& info)
        {
            unitree_api::msg::Request req;
            sportClient_.StopMove(req);
            RCLCPP_WARN(this->get_logger(),
                "[E-STOP/twist] STOP_MOVE sent. Triggered by ch='%s'",
                info.channel_name.empty() ? "(no active sink)" : info.channel_name.c_str());
        };

        server_->registerTypeConfig(std::move(twistCfg));

        RCLCPP_INFO(this->get_logger(),
            "ControlServerNode started. Listening on '%s/control_signal_reg'. "
            "Publishing Unitree sport requests at %ld ms interval.",
            serverName.c_str(), static_cast<long>(outputIntervalMs));
    }

private:
    SportClient sportClient_;
    std::unique_ptr<rv2_interfaces::rv2_server_control::ControlServer> server_;
};

RCLCPP_COMPONENTS_REGISTER_NODE(ControlServerNode)

